version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
    - pip install -r requirements.txt
    - wget https://kojipkgs.fedoraproject.org//packages/sqlite/3.8.11/1.fc21/x86_64/sqlite-3.8.11-1.fc21.x86_64.rpm
    - yum install sqlite-3.8.11-1.fc21.x86_64.rpm
  build:
    commands:
    - echo "Entered build phase"
    - python manage.py makemigrations
    - python manage.py migrate
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - echo Build completed on `date`
artifacts:
  files:
    - '**/*'