version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
    - pip install -r requirements.txt
    - wget https://www.sqlite.org/2019/sqlite-autoconf-3280000.tar.gz
    - tar zxvf sqlite-autoconf-3280000.tar.gz
    - ./configure
    - make
    - make install
  build:
    commands:
    - echo "Entered build phase"
    - python manage.py makemigrations
    - python manage.py migrate
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - echo Build completed on `date`
artifacts:
  files:
    - '**/*'