version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
    - pip install -r requirements.txt
    - apt-get install libsqlite3-dev
    - apt-get install sqlite3
  build:
    commands:
    - echo "Entered build phase"
    - python manage.py makemigrations
    - python manage.py migrate
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - echo Build completed on `date`
artifacts:
  files:
    - '**/*'